/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "listdir.h"
#include <errno.h>
#include <dirent.h>

extern int errno;
extern char *strdup();

readdir_ret *
readdir_1_svc(nametype *argp, struct svc_req *rqstp)
{
	static readdir_ret  result;
	DIR *dirPointer;
	struct dirent *d;
	namelist list;
	namelist *listPointer;	

	/* 
 	 * open directory
 	 */
	dirPointer = opendir(*argp);
	if (dirPointer == (DIR *)NULL) {
		result.err = errno;
		return &result;
	}

	/*
  	 * free previous memory
  	 */
	xdr_free((xdrproc_t)xdr_readdir_ret, (char *)&result);

	/*
 	 * collect directory entries
 	 */
	listPointer = &result.readdir_ret_u.list;
	while (d = readdir(dirPointer)) {
		list = *listPointer = (namenode *) malloc(sizeof(namenode));
		if (list == (namenode *) NULL) {
			result.err = EAGAIN;
			closedir(dirPointer);
			return &result;	
		}
		list->name = strdup(d->d_name);
		listPointer = &list->next;
	}
	*listPointer = (namelist)NULL;

        /*
         * return result
         */
	result.err = 0;
	closedir(dirPointer);
	return &result;
}
